### ISSUE TITLE
update VerveineJ after change in THasModifier

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/VerveineJ#23]
see issue [https://github.com/moosetechnology/Famix/pull/195#issuecomment-754478795](https://github.com/moosetechnology/Famix/pull/195#issuecomment-754478795)

**Comment by NicolasAnquetil** [comment]
Currently depends at least on fixing https://github.com/moosetechnology/Famix/issues/201

**Comment by badetitou** [comment]
Done

**Comment by badetitou** [comment]
Done for Compatibility (must be done in master)

**Comment by badetitou** [comment]
Done completly
