### ISSUE TITLE
Lombok compatibility

### ISSUE THREAD

**Issue by ghost** [moosetechnology/VerveineJ#40]
More a question than an issue perse. Is VerveineJ compatible with projects using lombok?

**Comment by NicolasAnquetil** [comment]
I don't think it will do what you hope:

It will accept the annotations of Lombok as any other annotation.

But it will not "interpret" them however, which means if it does not see a toString() method or accessors, it will not put them in the model.
Or actually, if they are used somewhere, they will probably be created as "stubs".

I am not sure however
