### ISSUE TITLE
Taking into account the concept of Interface in Famix Java

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/VerveineJ#46]
Interface has been added to Famix Java.
The merge is not yet done to be sure not breaking your model.
But it would be great that VerveineJ enables to create Interfaces.

**Comment by badetitou** [comment]
Hi

It should not be super hard to do. 

1. Export the new FamixJava metamodel from Pharo to .mse / .json using Fame ( documentation is done in the readme )
2. Import in FameJava the metamodel and generate the target FamixJava java code ( previous example are included in the repo )
3. Replace old FamixJava of verveineJ by new FamixJava
4. Fix the code to make tests pass. 
5. Fix the remaining tests with the old isInterface stuff ( I suppose so ) 

It should take 1 day/1.5 day to do everything

**Comment by badetitou** [comment]
Ref to anne branch: https://github.com/anneetien/Famix/tree/interfaceJava

**Comment by badetitou** [comment]
It has been integrated in Verveine v3.0.0
