### ISSUE TITLE
Classes were removed from the Java metamodel but still used here

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/VerveineJ#50]
Three classes were removed from the Famix Java metamodel (https://github.com/moosetechnology/Famix/issues/196) : 
- FamixJavaCaughtException
- FamixJavaDeclaredException
- FamixJavaThrownException

They are still used by VerveineJ.
Now we can't import models created with VerveineJ because it is using these classes.

**Comment by badetitou** [comment]
@LABSARI Can you precise here how we should change VerveineJ.
By what have been replaced 
- FamixJavaCaughtException
- FamixJavaDeclaredException
and 
- FamixJavaThrownException
